name: youtube_player_iframe_example
description: Demonstrates how to use the youtube_player_iframe plugin.
publish_to: none
version: 6.0.0

resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
      sdk: flutter
  youtube_player_iframe:
  go_router: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  icons_launcher: ^3.1.0

flutter:
  uses-material-design: true

icons_launcher:
  image_path: ../screenshots/logo.png
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
