name: youtube_player

workspace:
  - packages/youtube_player_flutter
  - packages/youtube_player_flutter/example
  - packages/youtube_player_iframe
  - packages/youtube_player_iframe/example
  - packages/youtube_player_iframe_web
  - packages/youtube_player_iframe_web/example

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

dev_dependencies:
  melos: ^7.8.0
  flutter_lints: ^6.0.0

melos:
  name: youtube_player
  repository: https://github.com/sarbagyastha/youtube_player_flutter
