name: youtube_player_flutter
description: Flutter plugin for playing or streaming inline YouTube videos using the official iFrame player API. Powered by youtube_player_iframe.
version: 10.0.0
repository: https://github.com/sarbagyastha/youtube_player_flutter
homepage: https://github.com/sarbagyastha/youtube_player_flutter/tree/main/packages/youtube_player_flutter

topics:
  - youtube
  - video
  - player
  - iframe
  - multimedia

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  youtube_player_iframe: ^6.0.0
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

dependency_overrides:
  youtube_player_iframe:
    path: ../youtube_player_iframe
